general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "None"
opacity = 1
startup_mode = "Maximized"


[font]
normal.family = "JetBrainsMono Nerd Font"
size = 12.0
